classdef TopLevelModule < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %TopLevelModule Auto-generated custom layer
    % Auto-generated by MATLAB on 09-Jul-2024 10:12:01
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
        Param_conv1
        Param_pool1
        Param_conv2
        Param_pool2
        Param_fc1
        Param_dropout1
        Param_fc2
    end
    
    properties
        % Non-Trainable Parameters
        Constant_57
        Constant_58
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        
    end
    
    methods
        function obj = TopLevelModule(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [view_47] = predict(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                channel_est_A_1.ops.validateInput(CallMethod_x_1,'');
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_A_1.ops.permuteInputToReversePyTorch(CallMethod_x_1, '');
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_A_1.ops.permuteToReversePyTorch(CallMethod_x_1, '*CT', '');
            end
            
            if ~contains(CallMethod_x_1_format,'U')
                [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', numel(CallMethod_x_1_format));
            end
            
            [view_47] = tracedPyTorchFunction(obj,CallMethod_x_1,false,"predict");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(view_47.value) == 'U'))
                view_47 = permute(view_47.value, fliplr(1:max(2,view_47.rank)));
            end
            
        end
        
        
        
        function [view_47] = forward(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                channel_est_A_1.ops.validateInput(CallMethod_x_1,'');
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_A_1.ops.permuteInputToReversePyTorch(CallMethod_x_1, '');
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_A_1.ops.permuteToReversePyTorch(CallMethod_x_1, '*CT', '');
            end
            
            if ~contains(CallMethod_x_1_format,'U')
                [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', numel(CallMethod_x_1_format));
            end
            
            [view_47] = tracedPyTorchFunction(obj,CallMethod_x_1,true,"forward");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(view_47.value) == 'U'))
                view_47 = permute(view_47.value, fliplr(1:max(2,view_47.rank)));
            end
            
        end
        
        
        
        function [view_47] = tracedPyTorchFunction(obj,CallMethod_x_1,isForward,predict)
            
            GetAttr_fc2_1 = obj.Param_fc2;
            
            
            GetAttr_dropout1_1 = obj.Param_dropout1;
            
            
            GetAttr_fc1_1 = obj.Param_fc1;
            
            
            GetAttr_pool2_1 = obj.Param_pool2;
            
            GetAttr_pool2_1_InputFormat1 = '*CT';
            
            GetAttr_conv2_1 = obj.Param_conv2;
            
            GetAttr_conv2_1_InputFormat1 = '*CT';
            
            GetAttr_pool1_1 = obj.Param_pool1;
            
            GetAttr_pool1_1_InputFormat1 = '*CT';
            
            GetAttr_conv1_1 = obj.Param_conv1;
            
            GetAttr_conv1_1_InputFormat1 = '*CT';
            
            
            [CallMethod_x_1_labelled] = channel_est_A_1.ops.labelWithPropagatedFormats(CallMethod_x_1, GetAttr_conv1_1_InputFormat1);
            [CallMethod_18] = GetAttr_conv1_1.(predict)(CallMethod_x_1_labelled.value);
            [CallMethod_18, CallMethod_18_format] = channel_est_A_1.ops.permuteToReversePyTorch(CallMethod_18, '*CT', '');
            if ~contains(CallMethod_18_format,'U')
                [CallMethod_18] = struct('value', CallMethod_18, 'rank', numel(CallMethod_18_format));
            else
                [CallMethod_18] = struct('value', CallMethod_18, 'rank', '');
            end
            
            [relu_input_1.value] = relu(CallMethod_18.value);
            relu_input_1.rank = CallMethod_18.rank;
            
            [relu_input_1_labelled] = channel_est_A_1.ops.labelWithPropagatedFormats(relu_input_1, GetAttr_pool1_1_InputFormat1);
            [CallMethod_23] = GetAttr_pool1_1.(predict)(relu_input_1_labelled.value);
            [CallMethod_23, CallMethod_23_format] = channel_est_A_1.ops.permuteToReversePyTorch(CallMethod_23, '*CT', '');
            if ~contains(CallMethod_23_format,'U')
                [CallMethod_23] = struct('value', CallMethod_23, 'rank', numel(CallMethod_23_format));
            else
                [CallMethod_23] = struct('value', CallMethod_23, 'rank', '');
            end
            
            
            [CallMethod_23_labelled] = channel_est_A_1.ops.labelWithPropagatedFormats(CallMethod_23, GetAttr_conv2_1_InputFormat1);
            [CallMethod_24] = GetAttr_conv2_1.(predict)(CallMethod_23_labelled.value);
            [CallMethod_24, CallMethod_24_format] = channel_est_A_1.ops.permuteToReversePyTorch(CallMethod_24, '*CT', '');
            if ~contains(CallMethod_24_format,'U')
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', numel(CallMethod_24_format));
            else
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', '');
            end
            
            [relu_input0_1.value] = relu(CallMethod_24.value);
            relu_input0_1.rank = CallMethod_24.rank;
            
            [relu_input0_1_labelled] = channel_est_A_1.ops.labelWithPropagatedFormats(relu_input0_1, GetAttr_pool2_1_InputFormat1);
            [CallMethod_29] = GetAttr_pool2_1.(predict)(relu_input0_1_labelled.value);
            [CallMethod_29, CallMethod_29_format] = channel_est_A_1.ops.permuteToReversePyTorch(CallMethod_29, '*CT', '');
            if ~contains(CallMethod_29_format,'U')
                [CallMethod_29] = struct('value', CallMethod_29, 'rank', numel(CallMethod_29_format));
            else
                [CallMethod_29] = struct('value', CallMethod_29, 'rank', '');
            end
            
            [Constant_57] = channel_est_A_1.ops.makeStructForConstant(int64(obj.Constant_57), int64(1), "Typed");
            [view_input1_1] = channel_est_A_1.ops.pyView(CallMethod_29, Constant_57);
            
            view_input1_1_labelled = view_input1_1;
            view_input1_1_labelled.value = permute(view_input1_1_labelled.value, fliplr(1:max(2,view_input1_1_labelled.rank)));
            [CallMethod_36,CallMethod_36_rank] = GetAttr_fc1_1.(predict)(view_input1_1_labelled.value,dlarray(ones(1,view_input1_1.rank),'UU'));
            [CallMethod_36, CallMethod_36_format] = channel_est_A_1.ops.permuteToReversePyTorch(CallMethod_36, '', int64(numel(CallMethod_36_rank)));
            if ~contains(CallMethod_36_format,'U')
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', numel(CallMethod_36_format));
            else
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', int64(numel(CallMethod_36_rank)));
            end
            
            [tanh_input2_1.value] = tanh(CallMethod_36.value);
            tanh_input2_1.rank = CallMethod_36.rank;
            
            tanh_input2_1_labelled = tanh_input2_1;
            tanh_input2_1_labelled.value = permute(tanh_input2_1_labelled.value, fliplr(1:max(2,tanh_input2_1_labelled.rank)));
            [CallMethod_41,CallMethod_41_rank] = GetAttr_dropout1_1.(predict)(tanh_input2_1_labelled.value,dlarray(ones(1,tanh_input2_1.rank),'UU'));
            [CallMethod_41, CallMethod_41_format] = channel_est_A_1.ops.permuteToReversePyTorch(CallMethod_41, '', int64(numel(CallMethod_41_rank)));
            if ~contains(CallMethod_41_format,'U')
                [CallMethod_41] = struct('value', CallMethod_41, 'rank', numel(CallMethod_41_format));
            else
                [CallMethod_41] = struct('value', CallMethod_41, 'rank', int64(numel(CallMethod_41_rank)));
            end
            
            
            CallMethod_41_labelled = CallMethod_41;
            CallMethod_41_labelled.value = permute(CallMethod_41_labelled.value, fliplr(1:max(2,CallMethod_41_labelled.rank)));
            [CallMethod_42,CallMethod_42_rank] = GetAttr_fc2_1.(predict)(CallMethod_41_labelled.value,dlarray(ones(1,CallMethod_41.rank),'UU'));
            [CallMethod_42, CallMethod_42_format] = channel_est_A_1.ops.permuteToReversePyTorch(CallMethod_42, '', int64(numel(CallMethod_42_rank)));
            if ~contains(CallMethod_42_format,'U')
                [CallMethod_42] = struct('value', CallMethod_42, 'rank', numel(CallMethod_42_format));
            else
                [CallMethod_42] = struct('value', CallMethod_42, 'rank', int64(numel(CallMethod_42_rank)));
            end
            
            [Constant_58] = channel_est_A_1.ops.makeStructForConstant(int64(obj.Constant_58), int64(1), "Typed");
            [view_47] = channel_est_A_1.ops.pyView(CallMethod_42, Constant_58);
        end
        
    end
end

