function [] = plot_confusion_matrix(snr, cm)
for isnr=1:length(snr)
    figure;
    curr_cm = round(squeeze(cm(isnr,:,:)));
    confusionchart(curr_cm, ...
        ["A","B","C","D","E","F"], ...
        "RowSummary",'row-normalized', ...
        "ColumnSummary","column-normalized",...
        'Normalization','row-normalized', ...
        'Title',strcat("Channel Classifier Confusion Matrix - SNR: ",num2str(snr(isnr)),"dB"))
    output_path = "results/per_figs";
    filename = sprintf("classifier_cm_snr_%ddB.png", snr(isnr));
    outfilename = fullfile(output_path, filename);
    saveas(gcf, outfilename);
end
figure;
confusionchart(squeeze(sum(cm,1)), ...
        ["A","B","C","D","E","F"], ...
        "RowSummary",'row-normalized', ...
        "ColumnSummary","column-normalized",...
        'Normalization','row-normalized', ...
        'Title',"Channel Classifier Confusion Matrix - All SNRs")
output_path = "results/per_figs";
filename = "classifier_cm_all_snr.png";
outfilename = fullfile(output_path, filename);
saveas(gcf, outfilename);