classdef conv_torchmangle40_Conv1d < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %conv_torchmangle40_Conv1d Auto-generated custom layer
    % Auto-generated by MATLAB on 09-Jul-2024 10:12:13
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
    end
    
    properties
        % Non-Trainable Parameters
        Constant_19
        Constant_15
        Constant_7
        Constant_11
        Constant_33
        Constant_34
        Constant_35
        Constant_36
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        Param_bias
        Param_weight
    end
    
    methods
        function obj = conv_torchmangle40_Conv1d(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [squeeze_23] = predict(obj,unsqueeze_argument1_1)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [unsqueeze_argument1_1, unsqueeze_argument1_1_format] = channel_est_E_1.ops.permuteToReversePyTorch(unsqueeze_argument1_1, '*CT', '');
            
            if ~contains(unsqueeze_argument1_1_format,'U')
                [unsqueeze_argument1_1] = struct('value', unsqueeze_argument1_1, 'rank', numel(unsqueeze_argument1_1_format));
            end
            
            [squeeze_23] = tracedPyTorchFunction(obj,unsqueeze_argument1_1,false,"predict");
            
            
            [squeeze_23] = channel_est_E_1.ops.labelWithPropagatedFormats(squeeze_23, "*CT");
            squeeze_23 = squeeze_23.value ;
            
        end
        
        
        
        function [squeeze_23] = forward(obj,unsqueeze_argument1_1)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [unsqueeze_argument1_1, unsqueeze_argument1_1_format] = channel_est_E_1.ops.permuteToReversePyTorch(unsqueeze_argument1_1, '*CT', '');
            
            if ~contains(unsqueeze_argument1_1_format,'U')
                [unsqueeze_argument1_1] = struct('value', unsqueeze_argument1_1, 'rank', numel(unsqueeze_argument1_1_format));
            end
            
            [squeeze_23] = tracedPyTorchFunction(obj,unsqueeze_argument1_1,true,"forward");
            
            
            [squeeze_23] = channel_est_E_1.ops.labelWithPropagatedFormats(squeeze_23, "*CT");
            squeeze_23 = squeeze_23.value ;
            
        end
        
        
        
        function [squeeze_23] = tracedPyTorchFunction(obj,unsqueeze_argument1_1,isForward,predict)
            
            [Constant_19] = channel_est_E_1.ops.makeStructForConstant(int64(obj.Constant_19), int64(0), "Typed");
            [Constant_15] = channel_est_E_1.ops.makeStructForConstant(int64(obj.Constant_15), int64(0), "Typed");
            [Constant_7] = channel_est_E_1.ops.makeStructForConstant(int64(obj.Constant_7), int64(0), "Typed");
            [Constant_11] = channel_est_E_1.ops.makeStructForConstant(int64(obj.Constant_11), int64(0), "Typed");
            GetAttr_bias_1 = obj.Param_bias;
            
            [GetAttr_bias_1] = struct('value', dlarray(GetAttr_bias_1,'UU'), 'rank', 1);
            
            GetAttr_weight_1 = obj.Param_weight;
            
            [GetAttr_weight_1] = struct('value', dlarray(GetAttr_weight_1,'UUU'), 'rank', 3);
            
            [unsqueeze_8] = channel_est_E_1.ops.pyUnsqueeze(unsqueeze_argument1_1, Constant_7);
            [Constant_33] = channel_est_E_1.ops.makeStructForConstant(int64(obj.Constant_33), int64(1), "Typed");
            [Constant_34] = channel_est_E_1.ops.makeStructForConstant(int64(obj.Constant_34), int64(1), "Typed");
            [Constant_35] = channel_est_E_1.ops.makeStructForConstant(int64(obj.Constant_35), int64(1), "Typed");
            [Constant_36] = channel_est_E_1.ops.makeStructForConstant(int64(obj.Constant_36), int64(1), "Typed");
            [convolution_21] = channel_est_E_1.ops.pyConvolution(unsqueeze_8, GetAttr_weight_1, GetAttr_bias_1, Constant_33, Constant_34, Constant_35, Constant_15, Constant_36, Constant_11);
            [squeeze_23] = channel_est_E_1.ops.pySqueeze(convolution_21, Constant_7);
        end
        
    end
end

