classdef aten__dropout7 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %aten__dropout7 Auto-generated custom layer
    % Auto-generated by MATLAB on 09-Jul-2024 10:12:10
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
    end
    
    properties
        % Non-Trainable Parameters
        dropout_3
        dropout_4
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        
    end
    
    methods
        function obj = aten__dropout7(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [dropout_input_1, dropout_input_1_rank] = predict(obj,dropout_argument1_1, dropout_argument1_1_rank)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [dropout_argument1_1, dropout_argument1_1_format] = channel_est_D_1.ops.permuteToReversePyTorch(dropout_argument1_1, '', numel(dropout_argument1_1_rank));
            [dropout_argument1_1] = struct('value', dropout_argument1_1, 'rank', int64(numel(dropout_argument1_1_rank)));
            
            [dropout_input_1] = tracedPyTorchFunction(obj,dropout_argument1_1,false,"predict");
            
            [dropout_input_1_rank] = ones([1,dropout_input_1.rank], 'single');
            dropout_input_1_rank = dlarray(dropout_input_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(dropout_input_1.value) == 'U'))
                dropout_input_1 = permute(dropout_input_1.value, fliplr(1:max(2,dropout_input_1.rank)));
            end
            
        end
        
        
        
        function [dropout_input_1, dropout_input_1_rank] = forward(obj,dropout_argument1_1, dropout_argument1_1_rank)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [dropout_argument1_1, dropout_argument1_1_format] = channel_est_D_1.ops.permuteToReversePyTorch(dropout_argument1_1, '', numel(dropout_argument1_1_rank));
            [dropout_argument1_1] = struct('value', dropout_argument1_1, 'rank', int64(numel(dropout_argument1_1_rank)));
            
            [dropout_input_1] = tracedPyTorchFunction(obj,dropout_argument1_1,true,"forward");
            
            [dropout_input_1_rank] = ones([1,dropout_input_1.rank], 'single');
            dropout_input_1_rank = dlarray(dropout_input_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(dropout_input_1.value) == 'U'))
                dropout_input_1 = permute(dropout_input_1.value, fliplr(1:max(2,dropout_input_1.rank)));
            end
            
        end
        
        
        
        function [dropout_input_1] = tracedPyTorchFunction(obj,dropout_argument1_1,isForward,predict)
            
            [dropout_3] = channel_est_D_1.ops.makeStructForConstant(single(obj.dropout_3), int64(0), "Typed");
            [dropout_4] = channel_est_D_1.ops.makeStructForConstant(int64(obj.dropout_4), int64(0), "Typed");
            [dropout_input_1] = channel_est_D_1.ops.pyDropout(dropout_argument1_1, dropout_3, isForward);
        end
        
    end
end

