classdef TopLevelModule < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %TopLevelModule Auto-generated custom layer
    % Auto-generated by MATLAB on 09-Jul-2024 10:12:10
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
        Param_conv1
        Param_pool1
        Param_conv2
        Param_pool2
        Param_conv3
        Param_fc1
        Param_dropout1
        Param_fc2
        Param_fc3
    end
    
    properties
        % Non-Trainable Parameters
        Constant_69
        Constant_70
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        
    end
    
    methods
        function obj = TopLevelModule(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [view_58] = predict(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                channel_est_D_1.ops.validateInput(CallMethod_x_1,'');
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_D_1.ops.permuteInputToReversePyTorch(CallMethod_x_1, '');
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_D_1.ops.permuteToReversePyTorch(CallMethod_x_1, '*CT', '');
            end
            
            if ~contains(CallMethod_x_1_format,'U')
                [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', numel(CallMethod_x_1_format));
            end
            
            [view_58] = tracedPyTorchFunction(obj,CallMethod_x_1,false,"predict");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(view_58.value) == 'U'))
                view_58 = permute(view_58.value, fliplr(1:max(2,view_58.rank)));
            end
            
        end
        
        
        
        function [view_58] = forward(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                channel_est_D_1.ops.validateInput(CallMethod_x_1,'');
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_D_1.ops.permuteInputToReversePyTorch(CallMethod_x_1, '');
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_D_1.ops.permuteToReversePyTorch(CallMethod_x_1, '*CT', '');
            end
            
            if ~contains(CallMethod_x_1_format,'U')
                [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', numel(CallMethod_x_1_format));
            end
            
            [view_58] = tracedPyTorchFunction(obj,CallMethod_x_1,true,"forward");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(view_58.value) == 'U'))
                view_58 = permute(view_58.value, fliplr(1:max(2,view_58.rank)));
            end
            
        end
        
        
        
        function [view_58] = tracedPyTorchFunction(obj,CallMethod_x_1,isForward,predict)
            
            GetAttr_fc3_1 = obj.Param_fc3;
            
            
            GetAttr_fc2_1 = obj.Param_fc2;
            
            
            GetAttr_dropout1_1 = obj.Param_dropout1;
            
            
            GetAttr_fc1_1 = obj.Param_fc1;
            
            
            GetAttr_conv3_1 = obj.Param_conv3;
            
            GetAttr_conv3_1_InputFormat1 = '*CT';
            
            GetAttr_pool2_1 = obj.Param_pool2;
            
            GetAttr_pool2_1_InputFormat1 = '*CT';
            
            GetAttr_conv2_1 = obj.Param_conv2;
            
            GetAttr_conv2_1_InputFormat1 = '*CT';
            
            GetAttr_pool1_1 = obj.Param_pool1;
            
            GetAttr_pool1_1_InputFormat1 = '*CT';
            
            GetAttr_conv1_1 = obj.Param_conv1;
            
            GetAttr_conv1_1_InputFormat1 = '*CT';
            
            
            [CallMethod_x_1_labelled] = channel_est_D_1.ops.labelWithPropagatedFormats(CallMethod_x_1, GetAttr_conv1_1_InputFormat1);
            [CallMethod_22] = GetAttr_conv1_1.(predict)(CallMethod_x_1_labelled.value);
            [CallMethod_22, CallMethod_22_format] = channel_est_D_1.ops.permuteToReversePyTorch(CallMethod_22, '*CT', '');
            if ~contains(CallMethod_22_format,'U')
                [CallMethod_22] = struct('value', CallMethod_22, 'rank', numel(CallMethod_22_format));
            else
                [CallMethod_22] = struct('value', CallMethod_22, 'rank', '');
            end
            
            [relu_input_1.value] = relu(CallMethod_22.value);
            relu_input_1.rank = CallMethod_22.rank;
            
            [relu_input_1_labelled] = channel_est_D_1.ops.labelWithPropagatedFormats(relu_input_1, GetAttr_pool1_1_InputFormat1);
            [CallMethod_27] = GetAttr_pool1_1.(predict)(relu_input_1_labelled.value);
            [CallMethod_27, CallMethod_27_format] = channel_est_D_1.ops.permuteToReversePyTorch(CallMethod_27, '*CT', '');
            if ~contains(CallMethod_27_format,'U')
                [CallMethod_27] = struct('value', CallMethod_27, 'rank', numel(CallMethod_27_format));
            else
                [CallMethod_27] = struct('value', CallMethod_27, 'rank', '');
            end
            
            
            [CallMethod_27_labelled] = channel_est_D_1.ops.labelWithPropagatedFormats(CallMethod_27, GetAttr_conv2_1_InputFormat1);
            [CallMethod_28] = GetAttr_conv2_1.(predict)(CallMethod_27_labelled.value);
            [CallMethod_28, CallMethod_28_format] = channel_est_D_1.ops.permuteToReversePyTorch(CallMethod_28, '*CT', '');
            if ~contains(CallMethod_28_format,'U')
                [CallMethod_28] = struct('value', CallMethod_28, 'rank', numel(CallMethod_28_format));
            else
                [CallMethod_28] = struct('value', CallMethod_28, 'rank', '');
            end
            
            [relu_input0_1.value] = relu(CallMethod_28.value);
            relu_input0_1.rank = CallMethod_28.rank;
            
            [relu_input0_1_labelled] = channel_est_D_1.ops.labelWithPropagatedFormats(relu_input0_1, GetAttr_pool2_1_InputFormat1);
            [CallMethod_34] = GetAttr_pool2_1.(predict)(relu_input0_1_labelled.value);
            [CallMethod_34, CallMethod_34_format] = channel_est_D_1.ops.permuteToReversePyTorch(CallMethod_34, '*CT', '');
            if ~contains(CallMethod_34_format,'U')
                [CallMethod_34] = struct('value', CallMethod_34, 'rank', numel(CallMethod_34_format));
            else
                [CallMethod_34] = struct('value', CallMethod_34, 'rank', '');
            end
            
            
            [CallMethod_34_labelled] = channel_est_D_1.ops.labelWithPropagatedFormats(CallMethod_34, GetAttr_conv3_1_InputFormat1);
            [CallMethod_35] = GetAttr_conv3_1.(predict)(CallMethod_34_labelled.value);
            [CallMethod_35, CallMethod_35_format] = channel_est_D_1.ops.permuteToReversePyTorch(CallMethod_35, '*CT', '');
            if ~contains(CallMethod_35_format,'U')
                [CallMethod_35] = struct('value', CallMethod_35, 'rank', numel(CallMethod_35_format));
            else
                [CallMethod_35] = struct('value', CallMethod_35, 'rank', '');
            end
            
            [relu_x0_1.value] = relu(CallMethod_35.value);
            relu_x0_1.rank = CallMethod_35.rank;
            [Constant_69] = channel_est_D_1.ops.makeStructForConstant(int64(obj.Constant_69), int64(1), "Typed");
            [view_input1_1] = channel_est_D_1.ops.pyView(relu_x0_1, Constant_69);
            
            view_input1_1_labelled = view_input1_1;
            view_input1_1_labelled.value = permute(view_input1_1_labelled.value, fliplr(1:max(2,view_input1_1_labelled.rank)));
            [CallMethod_46,CallMethod_46_rank] = GetAttr_fc1_1.(predict)(view_input1_1_labelled.value,dlarray(ones(1,view_input1_1.rank),'UU'));
            [CallMethod_46, CallMethod_46_format] = channel_est_D_1.ops.permuteToReversePyTorch(CallMethod_46, '', int64(numel(CallMethod_46_rank)));
            if ~contains(CallMethod_46_format,'U')
                [CallMethod_46] = struct('value', CallMethod_46, 'rank', numel(CallMethod_46_format));
            else
                [CallMethod_46] = struct('value', CallMethod_46, 'rank', int64(numel(CallMethod_46_rank)));
            end
            
            
            CallMethod_46_labelled = CallMethod_46;
            CallMethod_46_labelled.value = permute(CallMethod_46_labelled.value, fliplr(1:max(2,CallMethod_46_labelled.rank)));
            [CallMethod_47,CallMethod_47_rank] = GetAttr_dropout1_1.(predict)(CallMethod_46_labelled.value,dlarray(ones(1,CallMethod_46.rank),'UU'));
            [CallMethod_47, CallMethod_47_format] = channel_est_D_1.ops.permuteToReversePyTorch(CallMethod_47, '', int64(numel(CallMethod_47_rank)));
            if ~contains(CallMethod_47_format,'U')
                [CallMethod_47] = struct('value', CallMethod_47, 'rank', numel(CallMethod_47_format));
            else
                [CallMethod_47] = struct('value', CallMethod_47, 'rank', int64(numel(CallMethod_47_rank)));
            end
            
            
            CallMethod_47_labelled = CallMethod_47;
            CallMethod_47_labelled.value = permute(CallMethod_47_labelled.value, fliplr(1:max(2,CallMethod_47_labelled.rank)));
            [CallMethod_50,CallMethod_50_rank] = GetAttr_fc2_1.(predict)(CallMethod_47_labelled.value,dlarray(ones(1,CallMethod_47.rank),'UU'));
            [CallMethod_50, CallMethod_50_format] = channel_est_D_1.ops.permuteToReversePyTorch(CallMethod_50, '', int64(numel(CallMethod_50_rank)));
            if ~contains(CallMethod_50_format,'U')
                [CallMethod_50] = struct('value', CallMethod_50, 'rank', numel(CallMethod_50_format));
            else
                [CallMethod_50] = struct('value', CallMethod_50, 'rank', int64(numel(CallMethod_50_rank)));
            end
            
            [tanh_input2_1.value] = tanh(CallMethod_50.value);
            tanh_input2_1.rank = CallMethod_50.rank;
            
            tanh_input2_1_labelled = tanh_input2_1;
            tanh_input2_1_labelled.value = permute(tanh_input2_1_labelled.value, fliplr(1:max(2,tanh_input2_1_labelled.rank)));
            [CallMethod_54,CallMethod_54_rank] = GetAttr_fc3_1.(predict)(tanh_input2_1_labelled.value,dlarray(ones(1,tanh_input2_1.rank),'UU'));
            [CallMethod_54, CallMethod_54_format] = channel_est_D_1.ops.permuteToReversePyTorch(CallMethod_54, '', int64(numel(CallMethod_54_rank)));
            if ~contains(CallMethod_54_format,'U')
                [CallMethod_54] = struct('value', CallMethod_54, 'rank', numel(CallMethod_54_format));
            else
                [CallMethod_54] = struct('value', CallMethod_54, 'rank', int64(numel(CallMethod_54_rank)));
            end
            
            [Constant_70] = channel_est_D_1.ops.makeStructForConstant(int64(obj.Constant_70), int64(1), "Typed");
            [view_58] = channel_est_D_1.ops.pyView(CallMethod_54, Constant_70);
        end
        
    end
end

