classdef TopLevelModule < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %TopLevelModule Auto-generated custom layer
    % Auto-generated by MATLAB on 09-Jul-2024 10:12:08
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
        Param_conv1
        Param_pool1
        Param_conv2
        Param_pool2
        Param_fc1
        Param_dropout1
        Param_fc2
        Param_fc3
    end
    
    properties
        % Non-Trainable Parameters
        Constant_64
        Constant_65
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        
    end
    
    methods
        function obj = TopLevelModule(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [view_53] = predict(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                channel_est_C_1.ops.validateInput(CallMethod_x_1,'');
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_C_1.ops.permuteInputToReversePyTorch(CallMethod_x_1, '');
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_C_1.ops.permuteToReversePyTorch(CallMethod_x_1, '*CT', '');
            end
            
            if ~contains(CallMethod_x_1_format,'U')
                [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', numel(CallMethod_x_1_format));
            end
            
            [view_53] = tracedPyTorchFunction(obj,CallMethod_x_1,false,"predict");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(view_53.value) == 'U'))
                view_53 = permute(view_53.value, fliplr(1:max(2,view_53.rank)));
            end
            
        end
        
        
        
        function [view_53] = forward(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                channel_est_C_1.ops.validateInput(CallMethod_x_1,'');
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_C_1.ops.permuteInputToReversePyTorch(CallMethod_x_1, '');
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_C_1.ops.permuteToReversePyTorch(CallMethod_x_1, '*CT', '');
            end
            
            if ~contains(CallMethod_x_1_format,'U')
                [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', numel(CallMethod_x_1_format));
            end
            
            [view_53] = tracedPyTorchFunction(obj,CallMethod_x_1,true,"forward");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(view_53.value) == 'U'))
                view_53 = permute(view_53.value, fliplr(1:max(2,view_53.rank)));
            end
            
        end
        
        
        
        function [view_53] = tracedPyTorchFunction(obj,CallMethod_x_1,isForward,predict)
            
            GetAttr_fc3_1 = obj.Param_fc3;
            
            
            GetAttr_fc2_1 = obj.Param_fc2;
            
            
            GetAttr_dropout1_1 = obj.Param_dropout1;
            
            
            GetAttr_fc1_1 = obj.Param_fc1;
            
            
            GetAttr_pool2_1 = obj.Param_pool2;
            
            GetAttr_pool2_1_InputFormat1 = '*CT';
            
            GetAttr_conv2_1 = obj.Param_conv2;
            
            GetAttr_conv2_1_InputFormat1 = '*CT';
            
            GetAttr_pool1_1 = obj.Param_pool1;
            
            GetAttr_pool1_1_InputFormat1 = '*CT';
            
            GetAttr_conv1_1 = obj.Param_conv1;
            
            GetAttr_conv1_1_InputFormat1 = '*CT';
            
            
            [CallMethod_x_1_labelled] = channel_est_C_1.ops.labelWithPropagatedFormats(CallMethod_x_1, GetAttr_conv1_1_InputFormat1);
            [CallMethod_20] = GetAttr_conv1_1.(predict)(CallMethod_x_1_labelled.value);
            [CallMethod_20, CallMethod_20_format] = channel_est_C_1.ops.permuteToReversePyTorch(CallMethod_20, '*CT', '');
            if ~contains(CallMethod_20_format,'U')
                [CallMethod_20] = struct('value', CallMethod_20, 'rank', numel(CallMethod_20_format));
            else
                [CallMethod_20] = struct('value', CallMethod_20, 'rank', '');
            end
            
            [relu_input_1.value] = relu(CallMethod_20.value);
            relu_input_1.rank = CallMethod_20.rank;
            
            [relu_input_1_labelled] = channel_est_C_1.ops.labelWithPropagatedFormats(relu_input_1, GetAttr_pool1_1_InputFormat1);
            [CallMethod_25] = GetAttr_pool1_1.(predict)(relu_input_1_labelled.value);
            [CallMethod_25, CallMethod_25_format] = channel_est_C_1.ops.permuteToReversePyTorch(CallMethod_25, '*CT', '');
            if ~contains(CallMethod_25_format,'U')
                [CallMethod_25] = struct('value', CallMethod_25, 'rank', numel(CallMethod_25_format));
            else
                [CallMethod_25] = struct('value', CallMethod_25, 'rank', '');
            end
            
            
            [CallMethod_25_labelled] = channel_est_C_1.ops.labelWithPropagatedFormats(CallMethod_25, GetAttr_conv2_1_InputFormat1);
            [CallMethod_26] = GetAttr_conv2_1.(predict)(CallMethod_25_labelled.value);
            [CallMethod_26, CallMethod_26_format] = channel_est_C_1.ops.permuteToReversePyTorch(CallMethod_26, '*CT', '');
            if ~contains(CallMethod_26_format,'U')
                [CallMethod_26] = struct('value', CallMethod_26, 'rank', numel(CallMethod_26_format));
            else
                [CallMethod_26] = struct('value', CallMethod_26, 'rank', '');
            end
            
            [relu_input0_1.value] = relu(CallMethod_26.value);
            relu_input0_1.rank = CallMethod_26.rank;
            
            [relu_input0_1_labelled] = channel_est_C_1.ops.labelWithPropagatedFormats(relu_input0_1, GetAttr_pool2_1_InputFormat1);
            [CallMethod_31] = GetAttr_pool2_1.(predict)(relu_input0_1_labelled.value);
            [CallMethod_31, CallMethod_31_format] = channel_est_C_1.ops.permuteToReversePyTorch(CallMethod_31, '*CT', '');
            if ~contains(CallMethod_31_format,'U')
                [CallMethod_31] = struct('value', CallMethod_31, 'rank', numel(CallMethod_31_format));
            else
                [CallMethod_31] = struct('value', CallMethod_31, 'rank', '');
            end
            
            [Constant_64] = channel_est_C_1.ops.makeStructForConstant(int64(obj.Constant_64), int64(1), "Typed");
            [view_input1_1] = channel_est_C_1.ops.pyView(CallMethod_31, Constant_64);
            
            view_input1_1_labelled = view_input1_1;
            view_input1_1_labelled.value = permute(view_input1_1_labelled.value, fliplr(1:max(2,view_input1_1_labelled.rank)));
            [CallMethod_38,CallMethod_38_rank] = GetAttr_fc1_1.(predict)(view_input1_1_labelled.value,dlarray(ones(1,view_input1_1.rank),'UU'));
            [CallMethod_38, CallMethod_38_format] = channel_est_C_1.ops.permuteToReversePyTorch(CallMethod_38, '', int64(numel(CallMethod_38_rank)));
            if ~contains(CallMethod_38_format,'U')
                [CallMethod_38] = struct('value', CallMethod_38, 'rank', numel(CallMethod_38_format));
            else
                [CallMethod_38] = struct('value', CallMethod_38, 'rank', int64(numel(CallMethod_38_rank)));
            end
            
            [relu_input2_1.value] = relu(CallMethod_38.value);
            relu_input2_1.rank = CallMethod_38.rank;
            
            relu_input2_1_labelled = relu_input2_1;
            relu_input2_1_labelled.value = permute(relu_input2_1_labelled.value, fliplr(1:max(2,relu_input2_1_labelled.rank)));
            [CallMethod_43,CallMethod_43_rank] = GetAttr_dropout1_1.(predict)(relu_input2_1_labelled.value,dlarray(ones(1,relu_input2_1.rank),'UU'));
            [CallMethod_43, CallMethod_43_format] = channel_est_C_1.ops.permuteToReversePyTorch(CallMethod_43, '', int64(numel(CallMethod_43_rank)));
            if ~contains(CallMethod_43_format,'U')
                [CallMethod_43] = struct('value', CallMethod_43, 'rank', numel(CallMethod_43_format));
            else
                [CallMethod_43] = struct('value', CallMethod_43, 'rank', int64(numel(CallMethod_43_rank)));
            end
            
            
            CallMethod_43_labelled = CallMethod_43;
            CallMethod_43_labelled.value = permute(CallMethod_43_labelled.value, fliplr(1:max(2,CallMethod_43_labelled.rank)));
            [CallMethod_44,CallMethod_44_rank] = GetAttr_fc2_1.(predict)(CallMethod_43_labelled.value,dlarray(ones(1,CallMethod_43.rank),'UU'));
            [CallMethod_44, CallMethod_44_format] = channel_est_C_1.ops.permuteToReversePyTorch(CallMethod_44, '', int64(numel(CallMethod_44_rank)));
            if ~contains(CallMethod_44_format,'U')
                [CallMethod_44] = struct('value', CallMethod_44, 'rank', numel(CallMethod_44_format));
            else
                [CallMethod_44] = struct('value', CallMethod_44, 'rank', int64(numel(CallMethod_44_rank)));
            end
            
            [tanh_input3_1.value] = tanh(CallMethod_44.value);
            tanh_input3_1.rank = CallMethod_44.rank;
            
            tanh_input3_1_labelled = tanh_input3_1;
            tanh_input3_1_labelled.value = permute(tanh_input3_1_labelled.value, fliplr(1:max(2,tanh_input3_1_labelled.rank)));
            [CallMethod_49,CallMethod_49_rank] = GetAttr_fc3_1.(predict)(tanh_input3_1_labelled.value,dlarray(ones(1,tanh_input3_1.rank),'UU'));
            [CallMethod_49, CallMethod_49_format] = channel_est_C_1.ops.permuteToReversePyTorch(CallMethod_49, '', int64(numel(CallMethod_49_rank)));
            if ~contains(CallMethod_49_format,'U')
                [CallMethod_49] = struct('value', CallMethod_49, 'rank', numel(CallMethod_49_format));
            else
                [CallMethod_49] = struct('value', CallMethod_49, 'rank', int64(numel(CallMethod_49_rank)));
            end
            
            [Constant_65] = channel_est_C_1.ops.makeStructForConstant(int64(obj.Constant_65), int64(1), "Typed");
            [view_53] = channel_est_C_1.ops.pyView(CallMethod_49, Constant_65);
        end
        
    end
end

