classdef aten__linear9 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %aten__linear9 Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Jul-2024 19:08:10
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
    end
    
    properties
        % Non-Trainable Parameters
        
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        Param_weight
        Param_bias
    end
    
    methods
        function obj = aten__linear9(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [linear_x_1, linear_x_1_rank] = predict(obj,linear_argument1_1, linear_argument1_1_rank)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_argument1_1, linear_argument1_1_format] = classfier_1.ops.permuteToReversePyTorch(linear_argument1_1, '', numel(linear_argument1_1_rank));
            [linear_argument1_1] = struct('value', linear_argument1_1, 'rank', int64(numel(linear_argument1_1_rank)));
            
            [linear_x_1] = tracedPyTorchFunction(obj,linear_argument1_1,false,"predict");
            
            [linear_x_1_rank] = ones([1,linear_x_1.rank], 'single');
            linear_x_1_rank = dlarray(linear_x_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(linear_x_1.value) == 'U'))
                linear_x_1 = permute(linear_x_1.value, fliplr(1:max(2,linear_x_1.rank)));
            end
            
        end
        
        
        
        function [linear_x_1, linear_x_1_rank] = forward(obj,linear_argument1_1, linear_argument1_1_rank)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_argument1_1, linear_argument1_1_format] = classfier_1.ops.permuteToReversePyTorch(linear_argument1_1, '', numel(linear_argument1_1_rank));
            [linear_argument1_1] = struct('value', linear_argument1_1, 'rank', int64(numel(linear_argument1_1_rank)));
            
            [linear_x_1] = tracedPyTorchFunction(obj,linear_argument1_1,true,"forward");
            
            [linear_x_1_rank] = ones([1,linear_x_1.rank], 'single');
            linear_x_1_rank = dlarray(linear_x_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(linear_x_1.value) == 'U'))
                linear_x_1 = permute(linear_x_1.value, fliplr(1:max(2,linear_x_1.rank)));
            end
            
        end
        
        
        
        function [linear_x_1] = tracedPyTorchFunction(obj,linear_argument1_1,isForward,predict)
            
            linear_weight_1 = obj.Param_weight;
            
            [linear_weight_1] = struct('value', dlarray(linear_weight_1,'UU'), 'rank', 2);
            
            linear_bias_1 = obj.Param_bias;
            
            [linear_bias_1] = struct('value', dlarray(linear_bias_1,'UU'), 'rank', 1);
            
            [linear_x_1] = classfier_1.ops.pyLinear(linear_argument1_1, linear_weight_1, linear_bias_1);
        end
        
    end
end

