classdef aten__max_pool1d1 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %aten__max_pool1d1 Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Jul-2024 19:08:10
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
    end
    
    properties
        % Non-Trainable Parameters
        maxpool1d_22
        maxpool1d_23
        maxpool1d_24
        maxpool1d_25
        maxpool1d_10
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        
    end
    
    methods
        function obj = aten__max_pool1d1(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [maxpool1d_input0_1] = predict(obj,maxpool1d_input_1)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [maxpool1d_input_1, maxpool1d_input_1_format] = classfier_1.ops.permuteToReversePyTorch(maxpool1d_input_1, 'CT', 2);
            [maxpool1d_input_1] = struct('value', maxpool1d_input_1, 'rank', int64(2));
            
            [maxpool1d_input0_1] = tracedPyTorchFunction(obj,maxpool1d_input_1,false,"predict");
            
            
            [maxpool1d_input0_1] = classfier_1.ops.labelWithPropagatedFormats(maxpool1d_input0_1, "CT");
            maxpool1d_input0_1 = maxpool1d_input0_1.value ;
            
        end
        
        
        
        function [maxpool1d_input0_1] = forward(obj,maxpool1d_input_1)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [maxpool1d_input_1, maxpool1d_input_1_format] = classfier_1.ops.permuteToReversePyTorch(maxpool1d_input_1, 'CT', 2);
            [maxpool1d_input_1] = struct('value', maxpool1d_input_1, 'rank', int64(2));
            
            [maxpool1d_input0_1] = tracedPyTorchFunction(obj,maxpool1d_input_1,true,"forward");
            
            
            [maxpool1d_input0_1] = classfier_1.ops.labelWithPropagatedFormats(maxpool1d_input0_1, "CT");
            maxpool1d_input0_1 = maxpool1d_input0_1.value ;
            
        end
        
        
        
        function [maxpool1d_input0_1] = tracedPyTorchFunction(obj,maxpool1d_input_1,isForward,predict)
            
            [maxpool1d_22] = classfier_1.ops.makeStructForConstant(int64(obj.maxpool1d_22), int64(1), "Typed");
            [maxpool1d_23] = classfier_1.ops.makeStructForConstant(int64(obj.maxpool1d_23), int64(1), "Typed");
            [maxpool1d_24] = classfier_1.ops.makeStructForConstant(int64(obj.maxpool1d_24), int64(1), "Typed");
            [maxpool1d_25] = classfier_1.ops.makeStructForConstant(int64(obj.maxpool1d_25), int64(1), "Typed");
            [maxpool1d_10] = classfier_1.ops.makeStructForConstant(int64(obj.maxpool1d_10), int64(0), "Typed");
            [maxpool1d_input0_1] = classfier_1.ops.pyMaxPool1d(maxpool1d_input_1, maxpool1d_22, maxpool1d_23, maxpool1d_24, maxpool1d_25, maxpool1d_10);
        end
        
    end
end

