classdef TopLevelModule < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %TopLevelModule Auto-generated custom layer
    % Auto-generated by MATLAB on 04-Jul-2024 19:08:11
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
        Param_conv1
        Param_pool1
        Param_conv2
        Param_pool2
        Param_conv3
        Param_fc1
        Param_dropout1
        Param_fc2
        Param_dropout2
        Param_fc4
    end
    
    properties
        % Non-Trainable Parameters
        Constant_63
        Constant_62
        Constant_74
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        
    end
    
    methods
        function obj = TopLevelModule(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [logsoftmax_64] = predict(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                classfier_1.ops.validateInput(CallMethod_x_1,2);
                [CallMethod_x_1, CallMethod_x_1_format] = classfier_1.ops.permuteInputToReversePyTorch(CallMethod_x_1, 2);
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_x_1, 'CT', 2);
            end
            [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', int64(2));
            
            [logsoftmax_64] = tracedPyTorchFunction(obj,CallMethod_x_1,false,"predict");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(logsoftmax_64.value) == 'U'))
                logsoftmax_64 = permute(logsoftmax_64.value, fliplr(1:max(2,logsoftmax_64.rank)));
            end
            
        end
        
        
        
        function [logsoftmax_64] = forward(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                classfier_1.ops.validateInput(CallMethod_x_1,2);
                [CallMethod_x_1, CallMethod_x_1_format] = classfier_1.ops.permuteInputToReversePyTorch(CallMethod_x_1, 2);
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_x_1, 'CT', 2);
            end
            [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', int64(2));
            
            [logsoftmax_64] = tracedPyTorchFunction(obj,CallMethod_x_1,true,"forward");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(logsoftmax_64.value) == 'U'))
                logsoftmax_64 = permute(logsoftmax_64.value, fliplr(1:max(2,logsoftmax_64.rank)));
            end
            
        end
        
        
        
        function [logsoftmax_64] = tracedPyTorchFunction(obj,CallMethod_x_1,isForward,predict)
            
            [Constant_63] = classfier_1.ops.makeStructForConstant(double(obj.Constant_63), int64(0), "Typed");
            [Constant_62] = classfier_1.ops.makeStructForConstant(int64(obj.Constant_62), int64(0), "Typed");
            GetAttr_fc4_1 = obj.Param_fc4;
            
            
            GetAttr_dropout2_1 = obj.Param_dropout2;
            
            
            GetAttr_fc2_1 = obj.Param_fc2;
            
            
            GetAttr_dropout1_1 = obj.Param_dropout1;
            
            
            GetAttr_fc1_1 = obj.Param_fc1;
            
            
            GetAttr_conv3_1 = obj.Param_conv3;
            
            GetAttr_conv3_1_InputFormat1 = 'CT';
            
            GetAttr_pool2_1 = obj.Param_pool2;
            
            GetAttr_pool2_1_InputFormat1 = 'CT';
            
            GetAttr_conv2_1 = obj.Param_conv2;
            
            GetAttr_conv2_1_InputFormat1 = 'CT';
            
            GetAttr_pool1_1 = obj.Param_pool1;
            
            GetAttr_pool1_1_InputFormat1 = 'CT';
            
            GetAttr_conv1_1 = obj.Param_conv1;
            
            GetAttr_conv1_1_InputFormat1 = 'CT';
            
            
            [CallMethod_x_1_labelled] = classfier_1.ops.labelWithPropagatedFormats(CallMethod_x_1, GetAttr_conv1_1_InputFormat1);
            [CallMethod_24] = GetAttr_conv1_1.(predict)(CallMethod_x_1_labelled.value);
            [CallMethod_24, CallMethod_24_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_24, 'CT', '');
            if ~contains(CallMethod_24_format,'U')
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', numel(CallMethod_24_format));
            else
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', '');
            end
            
            [relu_input_1.value] = relu(CallMethod_24.value);
            relu_input_1.rank = CallMethod_24.rank;
            
            [relu_input_1_labelled] = classfier_1.ops.labelWithPropagatedFormats(relu_input_1, GetAttr_pool1_1_InputFormat1);
            [CallMethod_29] = GetAttr_pool1_1.(predict)(relu_input_1_labelled.value);
            [CallMethod_29, CallMethod_29_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_29, 'CT', '');
            if ~contains(CallMethod_29_format,'U')
                [CallMethod_29] = struct('value', CallMethod_29, 'rank', numel(CallMethod_29_format));
            else
                [CallMethod_29] = struct('value', CallMethod_29, 'rank', '');
            end
            
            
            [CallMethod_29_labelled] = classfier_1.ops.labelWithPropagatedFormats(CallMethod_29, GetAttr_conv2_1_InputFormat1);
            [CallMethod_30] = GetAttr_conv2_1.(predict)(CallMethod_29_labelled.value);
            [CallMethod_30, CallMethod_30_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_30, 'CT', '');
            if ~contains(CallMethod_30_format,'U')
                [CallMethod_30] = struct('value', CallMethod_30, 'rank', numel(CallMethod_30_format));
            else
                [CallMethod_30] = struct('value', CallMethod_30, 'rank', '');
            end
            
            [relu_input0_1.value] = relu(CallMethod_30.value);
            relu_input0_1.rank = CallMethod_30.rank;
            
            [relu_input0_1_labelled] = classfier_1.ops.labelWithPropagatedFormats(relu_input0_1, GetAttr_pool2_1_InputFormat1);
            [CallMethod_36] = GetAttr_pool2_1.(predict)(relu_input0_1_labelled.value);
            [CallMethod_36, CallMethod_36_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_36, 'CT', '');
            if ~contains(CallMethod_36_format,'U')
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', numel(CallMethod_36_format));
            else
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', '');
            end
            
            
            [CallMethod_36_labelled] = classfier_1.ops.labelWithPropagatedFormats(CallMethod_36, GetAttr_conv3_1_InputFormat1);
            [CallMethod_37] = GetAttr_conv3_1.(predict)(CallMethod_36_labelled.value);
            [CallMethod_37, CallMethod_37_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_37, 'CT', '');
            if ~contains(CallMethod_37_format,'U')
                [CallMethod_37] = struct('value', CallMethod_37, 'rank', numel(CallMethod_37_format));
            else
                [CallMethod_37] = struct('value', CallMethod_37, 'rank', '');
            end
            
            [relu_x0_1.value] = relu(CallMethod_37.value);
            relu_x0_1.rank = CallMethod_37.rank;
            [Constant_74] = classfier_1.ops.makeStructForConstant(int64(obj.Constant_74), int64(1), "Typed");
            [view_input1_1] = classfier_1.ops.pyView(relu_x0_1, Constant_74);
            
            view_input1_1_labelled = view_input1_1;
            view_input1_1_labelled.value = permute(view_input1_1_labelled.value, fliplr(1:max(2,view_input1_1_labelled.rank)));
            [CallMethod_47,CallMethod_47_rank] = GetAttr_fc1_1.(predict)(view_input1_1_labelled.value,dlarray(ones(1,view_input1_1.rank),'UU'));
            [CallMethod_47, CallMethod_47_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_47, '', int64(numel(CallMethod_47_rank)));
            if ~contains(CallMethod_47_format,'U')
                [CallMethod_47] = struct('value', CallMethod_47, 'rank', numel(CallMethod_47_format));
            else
                [CallMethod_47] = struct('value', CallMethod_47, 'rank', int64(numel(CallMethod_47_rank)));
            end
            
            [relu_input2_1.value] = relu(CallMethod_47.value);
            relu_input2_1.rank = CallMethod_47.rank;
            
            relu_input2_1_labelled = relu_input2_1;
            relu_input2_1_labelled.value = permute(relu_input2_1_labelled.value, fliplr(1:max(2,relu_input2_1_labelled.rank)));
            [CallMethod_52,CallMethod_52_rank] = GetAttr_dropout1_1.(predict)(relu_input2_1_labelled.value,dlarray(ones(1,relu_input2_1.rank),'UU'));
            [CallMethod_52, CallMethod_52_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_52, '', int64(numel(CallMethod_52_rank)));
            if ~contains(CallMethod_52_format,'U')
                [CallMethod_52] = struct('value', CallMethod_52, 'rank', numel(CallMethod_52_format));
            else
                [CallMethod_52] = struct('value', CallMethod_52, 'rank', int64(numel(CallMethod_52_rank)));
            end
            
            
            CallMethod_52_labelled = CallMethod_52;
            CallMethod_52_labelled.value = permute(CallMethod_52_labelled.value, fliplr(1:max(2,CallMethod_52_labelled.rank)));
            [CallMethod_53,CallMethod_53_rank] = GetAttr_fc2_1.(predict)(CallMethod_52_labelled.value,dlarray(ones(1,CallMethod_52.rank),'UU'));
            [CallMethod_53, CallMethod_53_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_53, '', int64(numel(CallMethod_53_rank)));
            if ~contains(CallMethod_53_format,'U')
                [CallMethod_53] = struct('value', CallMethod_53, 'rank', numel(CallMethod_53_format));
            else
                [CallMethod_53] = struct('value', CallMethod_53, 'rank', int64(numel(CallMethod_53_rank)));
            end
            
            [relu_input3_1.value] = relu(CallMethod_53.value);
            relu_input3_1.rank = CallMethod_53.rank;
            
            relu_input3_1_labelled = relu_input3_1;
            relu_input3_1_labelled.value = permute(relu_input3_1_labelled.value, fliplr(1:max(2,relu_input3_1_labelled.rank)));
            [CallMethod_59,CallMethod_59_rank] = GetAttr_dropout2_1.(predict)(relu_input3_1_labelled.value,dlarray(ones(1,relu_input3_1.rank),'UU'));
            [CallMethod_59, CallMethod_59_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_59, '', int64(numel(CallMethod_59_rank)));
            if ~contains(CallMethod_59_format,'U')
                [CallMethod_59] = struct('value', CallMethod_59, 'rank', numel(CallMethod_59_format));
            else
                [CallMethod_59] = struct('value', CallMethod_59, 'rank', int64(numel(CallMethod_59_rank)));
            end
            
            
            CallMethod_59_labelled = CallMethod_59;
            CallMethod_59_labelled.value = permute(CallMethod_59_labelled.value, fliplr(1:max(2,CallMethod_59_labelled.rank)));
            [CallMethod_60,CallMethod_60_rank] = GetAttr_fc4_1.(predict)(CallMethod_59_labelled.value,dlarray(ones(1,CallMethod_59.rank),'UU'));
            [CallMethod_60, CallMethod_60_format] = classfier_1.ops.permuteToReversePyTorch(CallMethod_60, '', int64(numel(CallMethod_60_rank)));
            if ~contains(CallMethod_60_format,'U')
                [CallMethod_60] = struct('value', CallMethod_60, 'rank', numel(CallMethod_60_format));
            else
                [CallMethod_60] = struct('value', CallMethod_60, 'rank', int64(numel(CallMethod_60_rank)));
            end
            
            [logsoftmax_64] = classfier_1.ops.pyLogSoftmax(CallMethod_60, Constant_62);
        end
        
    end
end

