classdef aten__linear2 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %aten__linear2 Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jul-2024 23:07:52
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
    end
    
    properties
        % Non-Trainable Parameters
        
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        Param_weight
        Param_bias
    end
    
    methods
        function obj = aten__linear2(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [linear_9] = predict(obj,linear_input_1)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_input_1, linear_input_1_format] = ds_E.ops.permuteToReversePyTorch(linear_input_1, 'CT', 2);
            [linear_input_1] = struct('value', linear_input_1, 'rank', int64(2));
            
            [linear_9] = tracedPyTorchFunction(obj,linear_input_1,false,"predict");
            
            
            [linear_9] = ds_E.ops.labelWithPropagatedFormats(linear_9, "CT");
            linear_9 = linear_9.value ;
            
        end
        
        
        
        function [linear_9] = forward(obj,linear_input_1)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_input_1, linear_input_1_format] = ds_E.ops.permuteToReversePyTorch(linear_input_1, 'CT', 2);
            [linear_input_1] = struct('value', linear_input_1, 'rank', int64(2));
            
            [linear_9] = tracedPyTorchFunction(obj,linear_input_1,true,"forward");
            
            
            [linear_9] = ds_E.ops.labelWithPropagatedFormats(linear_9, "CT");
            linear_9 = linear_9.value ;
            
        end
        
        
        
        function [linear_9] = tracedPyTorchFunction(obj,linear_input_1,isForward,predict)
            
            linear_weight_1 = obj.Param_weight;
            
            [linear_weight_1] = struct('value', dlarray(linear_weight_1,'UU'), 'rank', 2);
            
            linear_bias_1 = obj.Param_bias;
            
            [linear_bias_1] = struct('value', dlarray(linear_bias_1,'UU'), 'rank', 1);
            
            [linear_9] = ds_E.ops.pyLinear(linear_input_1, linear_weight_1, linear_bias_1);
        end
        
    end
end

