classdef aten__batch_norm4 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %aten__batch_norm4 Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jul-2024 23:07:53
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
    end
    
    properties
        % Non-Trainable Parameters
        batchnorm_15
        batchnorm_16
        batchnorm_17
        batchnorm_18
        
        
        Param_running_mean
        Param_running_var
    end
    
    properties (Learnable)
        % Trainable Parameters
        Param_weight
        Param_bias
    end
    
    methods
        function obj = aten__batch_norm4(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [batchnorm_x_1, batchnorm_x_1_rank] = predict(obj,batchnorm_input_1, batchnorm_input_1_rank)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [batchnorm_input_1, batchnorm_input_1_format] = ds_E.ops.permuteToReversePyTorch(batchnorm_input_1, '', numel(batchnorm_input_1_rank));
            [batchnorm_input_1] = struct('value', batchnorm_input_1, 'rank', int64(numel(batchnorm_input_1_rank)));
            
            [batchnorm_x_1] = tracedPyTorchFunction(obj,batchnorm_input_1,false,"predict");
            
            [batchnorm_x_1_rank] = ones([1,batchnorm_x_1.rank], 'single');
            batchnorm_x_1_rank = dlarray(batchnorm_x_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(batchnorm_x_1.value) == 'U'))
                batchnorm_x_1 = permute(batchnorm_x_1.value, fliplr(1:max(2,batchnorm_x_1.rank)));
            end
            
        end
        
        
        
        function [batchnorm_x_1, batchnorm_x_1_rank] = forward(obj,batchnorm_input_1, batchnorm_input_1_rank)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [batchnorm_input_1, batchnorm_input_1_format] = ds_E.ops.permuteToReversePyTorch(batchnorm_input_1, '', numel(batchnorm_input_1_rank));
            [batchnorm_input_1] = struct('value', batchnorm_input_1, 'rank', int64(numel(batchnorm_input_1_rank)));
            
            [batchnorm_x_1] = tracedPyTorchFunction(obj,batchnorm_input_1,true,"forward");
            
            [batchnorm_x_1_rank] = ones([1,batchnorm_x_1.rank], 'single');
            batchnorm_x_1_rank = dlarray(batchnorm_x_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(batchnorm_x_1.value) == 'U'))
                batchnorm_x_1 = permute(batchnorm_x_1.value, fliplr(1:max(2,batchnorm_x_1.rank)));
            end
            
        end
        
        
        
        function [batchnorm_x_1] = tracedPyTorchFunction(obj,batchnorm_input_1,isForward,predict)
            
            batchnorm_weight_1 = obj.Param_weight;
            
            [batchnorm_weight_1] = struct('value', dlarray(batchnorm_weight_1,'UU'), 'rank', 1);
            
            batchnorm_bias_1 = obj.Param_bias;
            
            [batchnorm_bias_1] = struct('value', dlarray(batchnorm_bias_1,'UU'), 'rank', 1);
            
            batchnorm_runningmean_1 = obj.Param_running_mean;
            
            [batchnorm_runningmean_1] = struct('value', dlarray(batchnorm_runningmean_1,'UU'), 'rank', 1);
            
            batchnorm_runningvar_1 = obj.Param_running_var;
            
            [batchnorm_runningvar_1] = struct('value', dlarray(batchnorm_runningvar_1,'UU'), 'rank', 1);
            
            [batchnorm_15] = ds_E.ops.makeStructForConstant(int64(obj.batchnorm_15), int64(0), "Typed");
            [batchnorm_16] = ds_E.ops.makeStructForConstant(single(obj.batchnorm_16), int64(0), "Typed");
            [batchnorm_17] = ds_E.ops.makeStructForConstant(single(obj.batchnorm_17), int64(0), "Typed");
            [batchnorm_18] = ds_E.ops.makeStructForConstant(int64(obj.batchnorm_18), int64(0), "Typed");
            [batchnorm_x_1] = ds_E.ops.pyBatchNorm(batchnorm_input_1, batchnorm_weight_1, batchnorm_bias_1, batchnorm_runningmean_1, batchnorm_runningvar_1, batchnorm_16, batchnorm_17, isForward);
        end
        
    end
end

