classdef TopLevelModule < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %TopLevelModule Auto-generated custom layer
    % Auto-generated by MATLAB on 06-Jul-2024 23:07:55
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
        Param_conv1
        Param_conv2
        Param_fc1
        Param_bn1
        Param_fc2
        Param_fc3
    end
    
    properties
        % Non-Trainable Parameters
        Constant_50
        Constant_51
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        
    end
    
    methods
        function obj = TopLevelModule(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [view_40] = predict(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                ds_E.ops.validateInput(CallMethod_x_1,2);
                [CallMethod_x_1, CallMethod_x_1_format] = ds_E.ops.permuteInputToReversePyTorch(CallMethod_x_1, 2);
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = ds_E.ops.permuteToReversePyTorch(CallMethod_x_1, 'CT', 2);
            end
            [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', int64(2));
            
            [view_40] = tracedPyTorchFunction(obj,CallMethod_x_1,false,"predict");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(view_40.value) == 'U'))
                view_40 = permute(view_40.value, fliplr(1:max(2,view_40.rank)));
            end
            
        end
        
        
        
        function [view_40] = forward(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                ds_E.ops.validateInput(CallMethod_x_1,2);
                [CallMethod_x_1, CallMethod_x_1_format] = ds_E.ops.permuteInputToReversePyTorch(CallMethod_x_1, 2);
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = ds_E.ops.permuteToReversePyTorch(CallMethod_x_1, 'CT', 2);
            end
            [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', int64(2));
            
            [view_40] = tracedPyTorchFunction(obj,CallMethod_x_1,true,"forward");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(view_40.value) == 'U'))
                view_40 = permute(view_40.value, fliplr(1:max(2,view_40.rank)));
            end
            
        end
        
        
        
        function [view_40] = tracedPyTorchFunction(obj,CallMethod_x_1,isForward,predict)
            
            GetAttr_fc3_1 = obj.Param_fc3;
            
            
            GetAttr_fc2_1 = obj.Param_fc2;
            
            
            GetAttr_bn1_1 = obj.Param_bn1;
            
            
            GetAttr_fc1_1 = obj.Param_fc1;
            
            GetAttr_fc1_1_InputFormat1 = 'CT';
            
            GetAttr_conv2_1 = obj.Param_conv2;
            
            GetAttr_conv2_1_InputFormat1 = 'CT';
            
            GetAttr_conv1_1 = obj.Param_conv1;
            
            GetAttr_conv1_1_InputFormat1 = 'CT';
            
            
            [CallMethod_x_1_labelled] = ds_E.ops.labelWithPropagatedFormats(CallMethod_x_1, GetAttr_conv1_1_InputFormat1);
            [CallMethod_16] = GetAttr_conv1_1.(predict)(CallMethod_x_1_labelled.value);
            [CallMethod_16, CallMethod_16_format] = ds_E.ops.permuteToReversePyTorch(CallMethod_16, 'CT', '');
            if ~contains(CallMethod_16_format,'U')
                [CallMethod_16] = struct('value', CallMethod_16, 'rank', numel(CallMethod_16_format));
            else
                [CallMethod_16] = struct('value', CallMethod_16, 'rank', '');
            end
            
            [relu_input_1.value] = relu(CallMethod_16.value);
            relu_input_1.rank = CallMethod_16.rank;
            
            [relu_input_1_labelled] = ds_E.ops.labelWithPropagatedFormats(relu_input_1, GetAttr_conv2_1_InputFormat1);
            [CallMethod_20] = GetAttr_conv2_1.(predict)(relu_input_1_labelled.value);
            [CallMethod_20, CallMethod_20_format] = ds_E.ops.permuteToReversePyTorch(CallMethod_20, 'CT', '');
            if ~contains(CallMethod_20_format,'U')
                [CallMethod_20] = struct('value', CallMethod_20, 'rank', numel(CallMethod_20_format));
            else
                [CallMethod_20] = struct('value', CallMethod_20, 'rank', '');
            end
            
            [relu_input0_1.value] = relu(CallMethod_20.value);
            relu_input0_1.rank = CallMethod_20.rank;
            
            [relu_input0_1_labelled] = ds_E.ops.labelWithPropagatedFormats(relu_input0_1, GetAttr_fc1_1_InputFormat1);
            [CallMethod_24] = GetAttr_fc1_1.(predict)(relu_input0_1_labelled.value);
            [CallMethod_24, CallMethod_24_format] = ds_E.ops.permuteToReversePyTorch(CallMethod_24, 'CT', '');
            if ~contains(CallMethod_24_format,'U')
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', numel(CallMethod_24_format));
            else
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', '');
            end
            
            [Constant_50] = ds_E.ops.makeStructForConstant(int64(obj.Constant_50), int64(1), "Typed");
            [view_input1_1] = ds_E.ops.pyView(CallMethod_24, Constant_50);
            
            view_input1_1_labelled = view_input1_1;
            view_input1_1_labelled.value = permute(view_input1_1_labelled.value, fliplr(1:max(2,view_input1_1_labelled.rank)));
            [CallMethod_31,CallMethod_31_rank] = GetAttr_bn1_1.(predict)(view_input1_1_labelled.value,dlarray(ones(1,view_input1_1.rank),'UU'));
            [CallMethod_31, CallMethod_31_format] = ds_E.ops.permuteToReversePyTorch(CallMethod_31, '', int64(numel(CallMethod_31_rank)));
            if ~contains(CallMethod_31_format,'U')
                [CallMethod_31] = struct('value', CallMethod_31, 'rank', numel(CallMethod_31_format));
            else
                [CallMethod_31] = struct('value', CallMethod_31, 'rank', int64(numel(CallMethod_31_rank)));
            end
            
            [relu_input2_1.value] = relu(CallMethod_31.value);
            relu_input2_1.rank = CallMethod_31.rank;
            
            relu_input2_1_labelled = relu_input2_1;
            relu_input2_1_labelled.value = permute(relu_input2_1_labelled.value, fliplr(1:max(2,relu_input2_1_labelled.rank)));
            [CallMethod_36,CallMethod_36_rank] = GetAttr_fc2_1.(predict)(relu_input2_1_labelled.value,dlarray(ones(1,relu_input2_1.rank),'UU'));
            [CallMethod_36, CallMethod_36_format] = ds_E.ops.permuteToReversePyTorch(CallMethod_36, '', int64(numel(CallMethod_36_rank)));
            if ~contains(CallMethod_36_format,'U')
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', numel(CallMethod_36_format));
            else
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', int64(numel(CallMethod_36_rank)));
            end
            
            
            CallMethod_36_labelled = CallMethod_36;
            CallMethod_36_labelled.value = permute(CallMethod_36_labelled.value, fliplr(1:max(2,CallMethod_36_labelled.rank)));
            [CallMethod_37,CallMethod_37_rank] = GetAttr_fc3_1.(predict)(CallMethod_36_labelled.value,dlarray(ones(1,CallMethod_36.rank),'UU'));
            [CallMethod_37, CallMethod_37_format] = ds_E.ops.permuteToReversePyTorch(CallMethod_37, '', int64(numel(CallMethod_37_rank)));
            if ~contains(CallMethod_37_format,'U')
                [CallMethod_37] = struct('value', CallMethod_37, 'rank', numel(CallMethod_37_format));
            else
                [CallMethod_37] = struct('value', CallMethod_37, 'rank', int64(numel(CallMethod_37_rank)));
            end
            
            [Constant_51] = ds_E.ops.makeStructForConstant(int64(obj.Constant_51), int64(1), "Typed");
            [view_40] = ds_E.ops.pyView(CallMethod_37, Constant_51);
        end
        
    end
end

