classdef aten__linear7 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %aten__linear7 Auto-generated custom layer
    % Auto-generated by MATLAB on 09-Jul-2024 10:12:15
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
    end
    
    properties
        % Non-Trainable Parameters
        
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        Param_weight
        Param_bias
    end
    
    methods
        function obj = aten__linear7(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [linear_9, linear_9_rank] = predict(obj,linear_input_1, linear_input_1_rank)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_input_1, linear_input_1_format] = channel_est_F_1.ops.permuteToReversePyTorch(linear_input_1, '', numel(linear_input_1_rank));
            [linear_input_1] = struct('value', linear_input_1, 'rank', int64(numel(linear_input_1_rank)));
            
            [linear_9] = tracedPyTorchFunction(obj,linear_input_1,false,"predict");
            
            [linear_9_rank] = ones([1,linear_9.rank], 'single');
            linear_9_rank = dlarray(linear_9_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(linear_9.value) == 'U'))
                linear_9 = permute(linear_9.value, fliplr(1:max(2,linear_9.rank)));
            end
            
        end
        
        
        
        function [linear_9, linear_9_rank] = forward(obj,linear_input_1, linear_input_1_rank)
            
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_input_1, linear_input_1_format] = channel_est_F_1.ops.permuteToReversePyTorch(linear_input_1, '', numel(linear_input_1_rank));
            [linear_input_1] = struct('value', linear_input_1, 'rank', int64(numel(linear_input_1_rank)));
            
            [linear_9] = tracedPyTorchFunction(obj,linear_input_1,true,"forward");
            
            [linear_9_rank] = ones([1,linear_9.rank], 'single');
            linear_9_rank = dlarray(linear_9_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(linear_9.value) == 'U'))
                linear_9 = permute(linear_9.value, fliplr(1:max(2,linear_9.rank)));
            end
            
        end
        
        
        
        function [linear_9] = tracedPyTorchFunction(obj,linear_input_1,isForward,predict)
            
            linear_weight_1 = obj.Param_weight;
            
            [linear_weight_1] = struct('value', dlarray(linear_weight_1,'UU'), 'rank', 2);
            
            linear_bias_1 = obj.Param_bias;
            
            [linear_bias_1] = struct('value', dlarray(linear_bias_1,'UU'), 'rank', 1);
            
            [linear_9] = channel_est_F_1.ops.pyLinear(linear_input_1, linear_weight_1, linear_bias_1);
        end
        
    end
end

