classdef TopLevelModule < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %TopLevelModule Auto-generated custom layer
    % Auto-generated by MATLAB on 09-Jul-2024 10:12:16
    
    properties (Learnable)
        % Networks (type dlnetwork)
        
        Param_conv1
        Param_pool1
        Param_conv2
        Param_pool2
        Param_conv3
        Param_pool3
        Param_fc1
        Param_dropout1
        Param_fc2
        Param_fc3
    end
    
    properties
        % Non-Trainable Parameters
        Constant_75
        Constant_76
        
        
        
    end
    
    properties (Learnable)
        % Trainable Parameters
        
    end
    
    methods
        function obj = TopLevelModule(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        
        function [view_64] = predict(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                channel_est_F_1.ops.validateInput(CallMethod_x_1,'');
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_F_1.ops.permuteInputToReversePyTorch(CallMethod_x_1, '');
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_x_1, '*CT', '');
            end
            
            if ~contains(CallMethod_x_1_format,'U')
                [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', numel(CallMethod_x_1_format));
            end
            
            [view_64] = tracedPyTorchFunction(obj,CallMethod_x_1,false,"predict");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(view_64.value) == 'U'))
                view_64 = permute(view_64.value, fliplr(1:max(2,view_64.rank)));
            end
            
        end
        
        
        
        function [view_64] = forward(obj,CallMethod_x_1)
            if any(dims(CallMethod_x_1) == 'U')
                %Validates that rank has been provided for U-labelled input
                channel_est_F_1.ops.validateInput(CallMethod_x_1,'');
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_F_1.ops.permuteInputToReversePyTorch(CallMethod_x_1, '');
            else
                
                %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
                [CallMethod_x_1, CallMethod_x_1_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_x_1, '*CT', '');
            end
            
            if ~contains(CallMethod_x_1_format,'U')
                [CallMethod_x_1] = struct('value', CallMethod_x_1, 'rank', numel(CallMethod_x_1_format));
            end
            
            [view_64] = tracedPyTorchFunction(obj,CallMethod_x_1,true,"forward");
            
            
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(view_64.value) == 'U'))
                view_64 = permute(view_64.value, fliplr(1:max(2,view_64.rank)));
            end
            
        end
        
        
        
        function [view_64] = tracedPyTorchFunction(obj,CallMethod_x_1,isForward,predict)
            
            GetAttr_fc3_1 = obj.Param_fc3;
            
            
            GetAttr_fc2_1 = obj.Param_fc2;
            
            
            GetAttr_dropout1_1 = obj.Param_dropout1;
            
            
            GetAttr_fc1_1 = obj.Param_fc1;
            
            
            GetAttr_pool3_1 = obj.Param_pool3;
            
            GetAttr_pool3_1_InputFormat1 = '*CT';
            
            GetAttr_conv3_1 = obj.Param_conv3;
            
            GetAttr_conv3_1_InputFormat1 = '*CT';
            
            GetAttr_pool2_1 = obj.Param_pool2;
            
            GetAttr_pool2_1_InputFormat1 = '*CT';
            
            GetAttr_conv2_1 = obj.Param_conv2;
            
            GetAttr_conv2_1_InputFormat1 = '*CT';
            
            GetAttr_pool1_1 = obj.Param_pool1;
            
            GetAttr_pool1_1_InputFormat1 = '*CT';
            
            GetAttr_conv1_1 = obj.Param_conv1;
            
            GetAttr_conv1_1_InputFormat1 = '*CT';
            
            
            [CallMethod_x_1_labelled] = channel_est_F_1.ops.labelWithPropagatedFormats(CallMethod_x_1, GetAttr_conv1_1_InputFormat1);
            [CallMethod_24] = GetAttr_conv1_1.(predict)(CallMethod_x_1_labelled.value);
            [CallMethod_24, CallMethod_24_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_24, '*CT', '');
            if ~contains(CallMethod_24_format,'U')
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', numel(CallMethod_24_format));
            else
                [CallMethod_24] = struct('value', CallMethod_24, 'rank', '');
            end
            
            [relu_input_1.value] = relu(CallMethod_24.value);
            relu_input_1.rank = CallMethod_24.rank;
            
            [relu_input_1_labelled] = channel_est_F_1.ops.labelWithPropagatedFormats(relu_input_1, GetAttr_pool1_1_InputFormat1);
            [CallMethod_29] = GetAttr_pool1_1.(predict)(relu_input_1_labelled.value);
            [CallMethod_29, CallMethod_29_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_29, '*CT', '');
            if ~contains(CallMethod_29_format,'U')
                [CallMethod_29] = struct('value', CallMethod_29, 'rank', numel(CallMethod_29_format));
            else
                [CallMethod_29] = struct('value', CallMethod_29, 'rank', '');
            end
            
            
            [CallMethod_29_labelled] = channel_est_F_1.ops.labelWithPropagatedFormats(CallMethod_29, GetAttr_conv2_1_InputFormat1);
            [CallMethod_30] = GetAttr_conv2_1.(predict)(CallMethod_29_labelled.value);
            [CallMethod_30, CallMethod_30_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_30, '*CT', '');
            if ~contains(CallMethod_30_format,'U')
                [CallMethod_30] = struct('value', CallMethod_30, 'rank', numel(CallMethod_30_format));
            else
                [CallMethod_30] = struct('value', CallMethod_30, 'rank', '');
            end
            
            [relu_input0_1.value] = relu(CallMethod_30.value);
            relu_input0_1.rank = CallMethod_30.rank;
            
            [relu_input0_1_labelled] = channel_est_F_1.ops.labelWithPropagatedFormats(relu_input0_1, GetAttr_pool2_1_InputFormat1);
            [CallMethod_36] = GetAttr_pool2_1.(predict)(relu_input0_1_labelled.value);
            [CallMethod_36, CallMethod_36_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_36, '*CT', '');
            if ~contains(CallMethod_36_format,'U')
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', numel(CallMethod_36_format));
            else
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', '');
            end
            
            
            [CallMethod_36_labelled] = channel_est_F_1.ops.labelWithPropagatedFormats(CallMethod_36, GetAttr_conv3_1_InputFormat1);
            [CallMethod_37] = GetAttr_conv3_1.(predict)(CallMethod_36_labelled.value);
            [CallMethod_37, CallMethod_37_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_37, '*CT', '');
            if ~contains(CallMethod_37_format,'U')
                [CallMethod_37] = struct('value', CallMethod_37, 'rank', numel(CallMethod_37_format));
            else
                [CallMethod_37] = struct('value', CallMethod_37, 'rank', '');
            end
            
            [relu_input1_1.value] = relu(CallMethod_37.value);
            relu_input1_1.rank = CallMethod_37.rank;
            
            [relu_input1_1_labelled] = channel_est_F_1.ops.labelWithPropagatedFormats(relu_input1_1, GetAttr_pool3_1_InputFormat1);
            [CallMethod_42] = GetAttr_pool3_1.(predict)(relu_input1_1_labelled.value);
            [CallMethod_42, CallMethod_42_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_42, '*CT', '');
            if ~contains(CallMethod_42_format,'U')
                [CallMethod_42] = struct('value', CallMethod_42, 'rank', numel(CallMethod_42_format));
            else
                [CallMethod_42] = struct('value', CallMethod_42, 'rank', '');
            end
            
            [Constant_75] = channel_est_F_1.ops.makeStructForConstant(int64(obj.Constant_75), int64(1), "Typed");
            [view_input2_1] = channel_est_F_1.ops.pyView(CallMethod_42, Constant_75);
            
            view_input2_1_labelled = view_input2_1;
            view_input2_1_labelled.value = permute(view_input2_1_labelled.value, fliplr(1:max(2,view_input2_1_labelled.rank)));
            [CallMethod_49,CallMethod_49_rank] = GetAttr_fc1_1.(predict)(view_input2_1_labelled.value,dlarray(ones(1,view_input2_1.rank),'UU'));
            [CallMethod_49, CallMethod_49_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_49, '', int64(numel(CallMethod_49_rank)));
            if ~contains(CallMethod_49_format,'U')
                [CallMethod_49] = struct('value', CallMethod_49, 'rank', numel(CallMethod_49_format));
            else
                [CallMethod_49] = struct('value', CallMethod_49, 'rank', int64(numel(CallMethod_49_rank)));
            end
            
            [relu_input3_1.value] = relu(CallMethod_49.value);
            relu_input3_1.rank = CallMethod_49.rank;
            
            relu_input3_1_labelled = relu_input3_1;
            relu_input3_1_labelled.value = permute(relu_input3_1_labelled.value, fliplr(1:max(2,relu_input3_1_labelled.rank)));
            [CallMethod_54,CallMethod_54_rank] = GetAttr_dropout1_1.(predict)(relu_input3_1_labelled.value,dlarray(ones(1,relu_input3_1.rank),'UU'));
            [CallMethod_54, CallMethod_54_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_54, '', int64(numel(CallMethod_54_rank)));
            if ~contains(CallMethod_54_format,'U')
                [CallMethod_54] = struct('value', CallMethod_54, 'rank', numel(CallMethod_54_format));
            else
                [CallMethod_54] = struct('value', CallMethod_54, 'rank', int64(numel(CallMethod_54_rank)));
            end
            
            
            CallMethod_54_labelled = CallMethod_54;
            CallMethod_54_labelled.value = permute(CallMethod_54_labelled.value, fliplr(1:max(2,CallMethod_54_labelled.rank)));
            [CallMethod_55,CallMethod_55_rank] = GetAttr_fc2_1.(predict)(CallMethod_54_labelled.value,dlarray(ones(1,CallMethod_54.rank),'UU'));
            [CallMethod_55, CallMethod_55_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_55, '', int64(numel(CallMethod_55_rank)));
            if ~contains(CallMethod_55_format,'U')
                [CallMethod_55] = struct('value', CallMethod_55, 'rank', numel(CallMethod_55_format));
            else
                [CallMethod_55] = struct('value', CallMethod_55, 'rank', int64(numel(CallMethod_55_rank)));
            end
            
            [tanh_input4_1.value] = tanh(CallMethod_55.value);
            tanh_input4_1.rank = CallMethod_55.rank;
            
            tanh_input4_1_labelled = tanh_input4_1;
            tanh_input4_1_labelled.value = permute(tanh_input4_1_labelled.value, fliplr(1:max(2,tanh_input4_1_labelled.rank)));
            [CallMethod_60,CallMethod_60_rank] = GetAttr_fc3_1.(predict)(tanh_input4_1_labelled.value,dlarray(ones(1,tanh_input4_1.rank),'UU'));
            [CallMethod_60, CallMethod_60_format] = channel_est_F_1.ops.permuteToReversePyTorch(CallMethod_60, '', int64(numel(CallMethod_60_rank)));
            if ~contains(CallMethod_60_format,'U')
                [CallMethod_60] = struct('value', CallMethod_60, 'rank', numel(CallMethod_60_format));
            else
                [CallMethod_60] = struct('value', CallMethod_60, 'rank', int64(numel(CallMethod_60_rank)));
            end
            
            [Constant_76] = channel_est_F_1.ops.makeStructForConstant(int64(obj.Constant_76), int64(1), "Typed");
            [view_64] = channel_est_F_1.ops.pyView(CallMethod_60, Constant_76);
        end
        
    end
end

